### ISSUE TITLE
Add and design a progress bar

### ISSUE THREAD

**Issue by falconx** [neontribe/spool#307]
Progress should indicate how far into the entry creation the user is.

**Comment by falconx** [comment]
@Stansbridge we'll have to think about how we can omit/change the display of the progress bar area depending on where we are in the app.

a) Homepage/dashboard: Omit it
b) Create entry: Progress meter
c) Individual entry pages: Show entry meta stuff

I guess we should have components which we pass through in the route definition since the header markup is defined at `App.js`.

**Comment by Stansbridge** [comment]
I've been working on this, we should chat tomorrow @falconx
