### ISSUE TITLE
Test output on iPad device

### ISSUE THREAD

**Issue by Stansbridge** [neontribe/spool#345]

**Comment by falconx** [comment]
Not working on the iPad 2 (iOS 7). A very low percentage of users are using this iOS version so we should be safe. We get a blank screen with no console errors. Something to do with Babel+Webpack which could be resolved on a prod build. Does work however on higher iOS versions. Only tested sign in screen so far.

**Comment by falconx** [comment]
Opened new ticket https://github.com/neontribe/spool/issues/411
