### ISSUE TITLE
Button focus exists after closing form

### ISSUE THREAD

**Issue by Stansbridge** [neontribe/spool#63]
Unsure whether this is intended or not, looks a little odd

![selection_081](https://cloud.githubusercontent.com/assets/1606432/17936300/3b875368-6a16-11e6-9b33-3887de37e031.png)

![selection_082](https://cloud.githubusercontent.com/assets/1606432/17936299/3b83638e-6a16-11e6-9b11-254326d02f6a.png)

![selection_080](https://cloud.githubusercontent.com/assets/1606432/17936301/3b8e085c-6a16-11e6-9b7e-131d39fb505b.png)

**Comment by marxian** [comment]
I found it odd too. I think it is because react-bootstrap is (correctly in a11y terms) throwing the focus back to the originating element on close...
